<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\Asteroid.png" />
    <None Remove="Images\Atom.png" />
    <None Remove="Images\Auto S1.png" />
    <None Remove="Images\Auto S2.png" />
    <None Remove="Images\Auto S3.png" />
    <None Remove="Images\Auto S4.png" />
    <None Remove="Images\Auto S5.png" />
    <None Remove="Images\Auto.png" />
    <None Remove="Images\Automatization.png" />
    <None Remove="Images\Better water.png" />
    <None Remove="Images\Black hole.png" />
    <None Remove="Images\Blue hypergiant.png" />
    <None Remove="Images\Boost Stage 1.png" />
    <None Remove="Images\Boost Stage 2.png" />
    <None Remove="Images\Boost Stage 3.png" />
    <None Remove="Images\Boost Stage 4.png" />
    <None Remove="Images\Boost Stage 5.png" />
    <None Remove="Images\Brown dwarf hot.png" />
    <None Remove="Images\Brown dwarf time hot.png" />
    <None Remove="Images\Brown dwarf time.png" />
    <None Remove="Images\Brown dwarf-.png" />
    <None Remove="Images\Brown dwarf.png" />
    <None Remove="Images\Cloud Researches.png" />
    <None Remove="Images\Clouds plus.png" />
    <None Remove="Images\Clouds.png" />
    <None Remove="Images\Collapse auto.png" />
    <None Remove="Images\Collapse Researches.png" />
    <None Remove="Images\Collapse toggle.png" />
    <None Remove="Images\Cosmic dust.png" />
    <None Remove="Images\Cosmic mass.png" />
    <None Remove="Images\Cosmon.png" />
    <None Remove="Images\Dark energy Researches.png" />
    <None Remove="Images\Dark energy.png" />
    <None Remove="Images\Dark fluid.png" />
    <None Remove="Images\Dark matter.png" />
    <None Remove="Images\Dark planet.png" />
    <None Remove="Images\Darkness.png" />
    <None Remove="Images\Discharge +1.png" />
    <None Remove="Images\Discharge auto.png" />
    <None Remove="Images\Discharge toggle.png" />
    <None Remove="Images\Drop.png" />
    <None Remove="Images\Drops recycle.png" />
    <None Remove="Images\Dust.png" />
    <None Remove="Images\Element0.png" />
    <None Remove="Images\Element1.png" />
    <None Remove="Images\Element10.png" />
    <None Remove="Images\Element11.png" />
    <None Remove="Images\Element12.png" />
    <None Remove="Images\Element13.png" />
    <None Remove="Images\Element14.png" />
    <None Remove="Images\Element15.png" />
    <None Remove="Images\Element16.png" />
    <None Remove="Images\Element17.png" />
    <None Remove="Images\Element18.png" />
    <None Remove="Images\Element19.png" />
    <None Remove="Images\Element2.png" />
    <None Remove="Images\Element20.png" />
    <None Remove="Images\Element21.png" />
    <None Remove="Images\Element22.png" />
    <None Remove="Images\Element23.png" />
    <None Remove="Images\Element24.png" />
    <None Remove="Images\Element25.png" />
    <None Remove="Images\Element26.png" />
    <None Remove="Images\Element27.png" />
    <None Remove="Images\Element28.png" />
    <None Remove="Images\Element29.png" />
    <None Remove="Images\Element3.png" />
    <None Remove="Images\Element30.png" />
    <None Remove="Images\Element31.png" />
    <None Remove="Images\Element32.png" />
    <None Remove="Images\Element33.png" />
    <None Remove="Images\Element34.png" />
    <None Remove="Images\Element35.png" />
    <None Remove="Images\Element36.png" />
    <None Remove="Images\Element4.png" />
    <None Remove="Images\Element5.png" />
    <None Remove="Images\Element6.png" />
    <None Remove="Images\Element7.png" />
    <None Remove="Images\Element8.png" />
    <None Remove="Images\Element9.png" />
    <None Remove="Images\Elements auto.png" />
    <None Remove="Images\Elements.png" />
    <None Remove="Images\End toggle.png" />
    <None Remove="Images\Energy mass.png" />
    <None Remove="Images\Energy Preon.png" />
    <None Remove="Images\Energy recycle.png" />
    <None Remove="Images\Energy Researches.png" />
    <None Remove="Images\Energy.png" />
    <None Remove="Images\False vacuum.png" />
    <None Remove="Images\Galactic tide.png" />
    <None Remove="Images\Galaxy auto.png" />
    <None Remove="Images\Galaxy group.png" />
    <None Remove="Images\Galaxy Researches.png" />
    <None Remove="Images\Galaxy.png" />
    <None Remove="Images\Giant.png" />
    <None Remove="Images\Gravitational bound.png" />
    <None Remove="Images\Inflaton.png" />
    <None Remove="Images\Instability.png" />
    <None Remove="Images\Lake.png" />
    <None Remove="Images\Light matter.png" />
    <None Remove="Images\Light planet.png" />
    <None Remove="Images\Main_sequence mass.png" />
    <None Remove="Images\Mass recycle.png" />
    <None Remove="Images\Mass-.png" />
    <None Remove="Images\Mass.png" />
    <None Remove="Images\Merge auto.png" />
    <None Remove="Images\Merge toggle.png" />
    <None Remove="Images\Meteoroids.png" />
    <None Remove="Images\Milestones.png" />
    <None Remove="Images\Missing.png" />
    <None Remove="Images\Molecule.png" />
    <None Remove="Images\More Cosmon.png" />
    <None Remove="Images\Natural satellite.png" />
    <None Remove="Images\Nebula+.png" />
    <None Remove="Images\Nebula.png" />
    <None Remove="Images\Neutron star.png" />
    <None Remove="Images\Neutronium.png" />
    <None Remove="Images\Nucleation toggle.png" />
    <None Remove="Images\Ocean world.png" />
    <None Remove="Images\Ocean.png" />
    <None Remove="Images\Offline.png" />
    <None Remove="Images\Orange dwarf.png" />
    <None Remove="Images\Particle+.png" />
    <None Remove="Images\Particle.png" />
    <None Remove="Images\Planet.png" />
    <None Remove="Images\Planetesimal.png" />
    <None Remove="Images\Pond.png" />
    <None Remove="Images\Preon.png" />
    <None Remove="Images\Protogalaxy.png" />
    <None Remove="Images\Protoplanet.png" />
    <None Remove="Images\Protostar.png" />
    <None Remove="Images\Puddle big.png" />
    <None Remove="Images\Puddle.png" />
    <None Remove="Images\Quark star.png" />
    <None Remove="Images\Quarks.png" />
    <None Remove="Images\Quasi star.png" />
    <None Remove="Images\Rank auto.png" />
    <None Remove="Images\Rank improvement.png" />
    <None Remove="Images\Rank levels.png" />
    <None Remove="Images\Rank max.png" />
    <None Remove="Images\Rank Researches.png" />
    <None Remove="Images\Rank toggle.png" />
    <None Remove="Images\Red giant+.png" />
    <None Remove="Images\Red giant.png" />
    <None Remove="Images\Red supergiant.png" />
    <None Remove="Images\ResearchA1.png" />
    <None Remove="Images\ResearchA2.png" />
    <None Remove="Images\ResearchA3.png" />
    <None Remove="Images\ResearchA4.png" />
    <None Remove="Images\ResearchA5.png" />
    <None Remove="Images\ResearchA6.png" />
    <None Remove="Images\ResearchA7.png" />
    <None Remove="Images\ResearchA8.png" />
    <None Remove="Images\ResearchA9.png" />
    <None Remove="Images\ResearchAuto1.png" />
    <None Remove="Images\ResearchAuto2.png" />
    <None Remove="Images\ResearchAuto3.png" />
    <None Remove="Images\ResearchClouds1.png" />
    <None Remove="Images\ResearchClouds2.png" />
    <None Remove="Images\ResearchClouds3.png" />
    <None Remove="Images\ResearchClouds4.png" />
    <None Remove="Images\ResearchClouds5.png" />
    <None Remove="Images\ResearchCollapse1.png" />
    <None Remove="Images\ResearchCollapse2.png" />
    <None Remove="Images\ResearchCollapse3.png" />
    <None Remove="Images\ResearchCollapse4.png" />
    <None Remove="Images\ResearchD1.png" />
    <None Remove="Images\ResearchD1_L.png" />
    <None Remove="Images\ResearchD2.png" />
    <None Remove="Images\ResearchD3.png" />
    <None Remove="Images\ResearchD3_L.png" />
    <None Remove="Images\ResearchD4.png" />
    <None Remove="Images\ResearchD5.png" />
    <None Remove="Images\ResearchDark1.png" />
    <None Remove="Images\ResearchDark1_L.png" />
    <None Remove="Images\ResearchDark2.png" />
    <None Remove="Images\ResearchDark3.png" />
    <None Remove="Images\ResearchDark4.png" />
    <None Remove="Images\ResearchDark4_L.png" />
    <None Remove="Images\ResearchDark5.png" />
    <None Remove="Images\ResearchEnergy1.png" />
    <None Remove="Images\ResearchEnergy2.png" />
    <None Remove="Images\ResearchEnergy3.png" />
    <None Remove="Images\ResearchEnergy4.png" />
    <None Remove="Images\ResearchEnergy5.png" />
    <None Remove="Images\ResearchEnergy6.png" />
    <None Remove="Images\ResearchG1.png" />
    <None Remove="Images\ResearchG2.png" />
    <None Remove="Images\ResearchG3.png" />
    <None Remove="Images\ResearchG4.png" />
    <None Remove="Images\ResearchGalaxy1.png" />
    <None Remove="Images\ResearchGalaxy2.png" />
    <None Remove="Images\ResearchGalaxy3.png" />
    <None Remove="Images\ResearchGalaxy4.png" />
    <None Remove="Images\ResearchQ1.png" />
    <None Remove="Images\ResearchQ2.png" />
    <None Remove="Images\ResearchQ3.png" />
    <None Remove="Images\ResearchQ4.png" />
    <None Remove="Images\ResearchQ5.png" />
    <None Remove="Images\ResearchQ6.png" />
    <None Remove="Images\ResearchRank1.png" />
    <None Remove="Images\ResearchRank2.png" />
    <None Remove="Images\ResearchRank3.png" />
    <None Remove="Images\ResearchRank4.png" />
    <None Remove="Images\ResearchRank5.png" />
    <None Remove="Images\ResearchRank6.png" />
    <None Remove="Images\ResearchS1.png" />
    <None Remove="Images\ResearchS2.png" />
    <None Remove="Images\ResearchS3.png" />
    <None Remove="Images\ResearchS4.png" />
    <None Remove="Images\ResearchS5.png" />
    <None Remove="Images\ResearchS6.png" />
    <None Remove="Images\ResearchW1.png" />
    <None Remove="Images\ResearchW2.png" />
    <None Remove="Images\ResearchW3.png" />
    <None Remove="Images\ResearchW4.png" />
    <None Remove="Images\ResearchW5.png" />
    <None Remove="Images\ResearchW6.png" />
    <None Remove="Images\Sea.png" />
    <None Remove="Images\Spread 2.png" />
    <None Remove="Images\Spread.png" />
    <None Remove="Images\Stability.png" />
    <None Remove="Images\Stage auto.png" />
    <None Remove="Images\Stage toggle.png" />
    <None Remove="Images\Stage.png" />
    <None Remove="Images\Stage1 border.png" />
    <None Remove="Images\Stage2 border.png" />
    <None Remove="Images\Stage3 border.png" />
    <None Remove="Images\Stage4 border.png" />
    <None Remove="Images\Stage5 border.png" />
    <None Remove="Images\Stage6 border.png" />
    <None Remove="Images\Star cluster denser.png" />
    <None Remove="Images\Star cluster.png" />
    <None Remove="Images\Stars.png" />
    <None Remove="Images\Strange growth.png" />
    <None Remove="Images\Strange Quarks many.png" />
    <None Remove="Images\Strange Quarks.png" />
    <None Remove="Images\Strangelets many.png" />
    <None Remove="Images\Strangelets.png" />
    <None Remove="Images\Subsatellite.png" />
    <None Remove="Images\System red.png" />
    <None Remove="Images\Time fast.png" />
    <None Remove="Images\Time.png" />
    <None Remove="Images\Universe.png" />
    <None Remove="Images\UpgradeA1.png" />
    <None Remove="Images\UpgradeA10.png" />
    <None Remove="Images\UpgradeA11.png" />
    <None Remove="Images\UpgradeA12.png" />
    <None Remove="Images\UpgradeA13.png" />
    <None Remove="Images\UpgradeA14.png" />
    <None Remove="Images\UpgradeA2.png" />
    <None Remove="Images\UpgradeA3.png" />
    <None Remove="Images\UpgradeA4.png" />
    <None Remove="Images\UpgradeA5.png" />
    <None Remove="Images\UpgradeA6.png" />
    <None Remove="Images\UpgradeA7.png" />
    <None Remove="Images\UpgradeA8.png" />
    <None Remove="Images\UpgradeA9.png" />
    <None Remove="Images\UpgradeD1.png" />
    <None Remove="Images\UpgradeD1_L.png" />
    <None Remove="Images\UpgradeG1.png" />
    <None Remove="Images\UpgradeG2.png" />
    <None Remove="Images\UpgradeG3.png" />
    <None Remove="Images\UpgradeG4.png" />
    <None Remove="Images\UpgradeG5.png" />
    <None Remove="Images\UpgradeG6.png" />
    <None Remove="Images\UpgradeG7.png" />
    <None Remove="Images\UpgradeQ1.png" />
    <None Remove="Images\UpgradeQ10.png" />
    <None Remove="Images\UpgradeQ11.png" />
    <None Remove="Images\UpgradeQ2.png" />
    <None Remove="Images\UpgradeQ3.png" />
    <None Remove="Images\UpgradeQ3_A.png" />
    <None Remove="Images\UpgradeQ4.png" />
    <None Remove="Images\UpgradeQ4_A.png" />
    <None Remove="Images\UpgradeQ5.png" />
    <None Remove="Images\UpgradeQ5_A.png" />
    <None Remove="Images\UpgradeQ6.png" />
    <None Remove="Images\UpgradeQ7.png" />
    <None Remove="Images\UpgradeQ8.png" />
    <None Remove="Images\UpgradeQ9.png" />
    <None Remove="Images\Upgrades auto.png" />
    <None Remove="Images\UpgradeS1.png" />
    <None Remove="Images\UpgradeS2.png" />
    <None Remove="Images\UpgradeS3.png" />
    <None Remove="Images\UpgradeS4.png" />
    <None Remove="Images\UpgradeS5.png" />
    <None Remove="Images\UpgradeW1.png" />
    <None Remove="Images\UpgradeW2.png" />
    <None Remove="Images\UpgradeW3.png" />
    <None Remove="Images\UpgradeW4.png" />
    <None Remove="Images\UpgradeW5.png" />
    <None Remove="Images\UpgradeW6.png" />
    <None Remove="Images\UpgradeW7.png" />
    <None Remove="Images\UpgradeW8.png" />
    <None Remove="Images\UpgradeW9.png" />
    <None Remove="Images\Vaporization auto.png" />
    <None Remove="Images\Vaporization improvement.png" />
    <None Remove="Images\Vaporization toggle.png" />
    <None Remove="Images\Void.png" />
    <None Remove="Images\Water+.png" />
    <None Remove="Images\Water.png" />
    <None Remove="Images\White dwarf.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Asteroid.png" />
    <Resource Include="Images\Atom.png" />
    <Resource Include="Images\Auto S1.png" />
    <Resource Include="Images\Auto S2.png" />
    <Resource Include="Images\Auto S3.png" />
    <Resource Include="Images\Auto S4.png" />
    <Resource Include="Images\Auto S5.png" />
    <Resource Include="Images\Auto.png" />
    <Resource Include="Images\Automatization.png" />
    <Resource Include="Images\Better water.png" />
    <Resource Include="Images\Black hole.png" />
    <Resource Include="Images\Blue hypergiant.png" />
    <Resource Include="Images\Boost Stage 1.png" />
    <Resource Include="Images\Boost Stage 2.png" />
    <Resource Include="Images\Boost Stage 3.png" />
    <Resource Include="Images\Boost Stage 4.png" />
    <Resource Include="Images\Boost Stage 5.png" />
    <Resource Include="Images\Brown dwarf hot.png" />
    <Resource Include="Images\Brown dwarf time hot.png" />
    <Resource Include="Images\Brown dwarf time.png" />
    <Resource Include="Images\Brown dwarf-.png" />
    <Resource Include="Images\Brown dwarf.png" />
    <Resource Include="Images\Cloud Researches.png" />
    <Resource Include="Images\Clouds plus.png" />
    <Resource Include="Images\Clouds.png" />
    <Resource Include="Images\Collapse auto.png" />
    <Resource Include="Images\Collapse Researches.png" />
    <Resource Include="Images\Collapse toggle.png" />
    <Resource Include="Images\Cosmic dust.png" />
    <Resource Include="Images\Cosmic mass.png" />
    <Resource Include="Images\Cosmon.png" />
    <Resource Include="Images\Dark energy Researches.png" />
    <Resource Include="Images\Dark energy.png" />
    <Resource Include="Images\Dark fluid.png" />
    <Resource Include="Images\Dark matter.png" />
    <Resource Include="Images\Dark planet.png" />
    <Resource Include="Images\Darkness.png" />
    <Resource Include="Images\Discharge +1.png" />
    <Resource Include="Images\Discharge auto.png" />
    <Resource Include="Images\Discharge toggle.png" />
    <Resource Include="Images\Drop.png" />
    <Resource Include="Images\Drops recycle.png" />
    <Resource Include="Images\Dust.png" />
    <Resource Include="Images\Element0.png" />
    <Resource Include="Images\Element1.png" />
    <Resource Include="Images\Element10.png" />
    <Resource Include="Images\Element11.png" />
    <Resource Include="Images\Element12.png" />
    <Resource Include="Images\Element13.png" />
    <Resource Include="Images\Element14.png" />
    <Resource Include="Images\Element15.png" />
    <Resource Include="Images\Element16.png" />
    <Resource Include="Images\Element17.png" />
    <Resource Include="Images\Element18.png" />
    <Resource Include="Images\Element19.png" />
    <Resource Include="Images\Element2.png" />
    <Resource Include="Images\Element20.png" />
    <Resource Include="Images\Element21.png" />
    <Resource Include="Images\Element22.png" />
    <Resource Include="Images\Element23.png" />
    <Resource Include="Images\Element24.png" />
    <Resource Include="Images\Element25.png" />
    <Resource Include="Images\Element26.png" />
    <Resource Include="Images\Element27.png" />
    <Resource Include="Images\Element28.png" />
    <Resource Include="Images\Element29.png" />
    <Resource Include="Images\Element3.png" />
    <Resource Include="Images\Element30.png" />
    <Resource Include="Images\Element31.png" />
    <Resource Include="Images\Element32.png" />
    <Resource Include="Images\Element33.png" />
    <Resource Include="Images\Element34.png" />
    <Resource Include="Images\Element35.png" />
    <Resource Include="Images\Element36.png" />
    <Resource Include="Images\Element4.png" />
    <Resource Include="Images\Element5.png" />
    <Resource Include="Images\Element6.png" />
    <Resource Include="Images\Element7.png" />
    <Resource Include="Images\Element8.png" />
    <Resource Include="Images\Element9.png" />
    <Resource Include="Images\Elements auto.png" />
    <Resource Include="Images\Elements.png" />
    <Resource Include="Images\End toggle.png" />
    <Resource Include="Images\Energy mass.png" />
    <Resource Include="Images\Energy Preon.png" />
    <Resource Include="Images\Energy recycle.png" />
    <Resource Include="Images\Energy Researches.png" />
    <Resource Include="Images\Energy.png" />
    <Resource Include="Images\False vacuum.png" />
    <Resource Include="Images\Galactic tide.png" />
    <Resource Include="Images\Galaxy auto.png" />
    <Resource Include="Images\Galaxy group.png" />
    <Resource Include="Images\Galaxy Researches.png" />
    <Resource Include="Images\Galaxy.png" />
    <Resource Include="Images\Giant.png" />
    <Resource Include="Images\Gravitational bound.png" />
    <Resource Include="Images\Inflaton.png" />
    <Resource Include="Images\Instability.png" />
    <Resource Include="Images\Lake.png" />
    <Resource Include="Images\Light matter.png" />
    <Resource Include="Images\Light planet.png" />
    <Resource Include="Images\Main_sequence mass.png" />
    <Resource Include="Images\Mass recycle.png" />
    <Resource Include="Images\Mass-.png" />
    <Resource Include="Images\Mass.png" />
    <Resource Include="Images\Merge auto.png" />
    <Resource Include="Images\Merge toggle.png" />
    <Resource Include="Images\Meteoroids.png" />
    <Resource Include="Images\Milestones.png" />
    <Resource Include="Images\Missing.png" />
    <Resource Include="Images\Molecule.png" />
    <Resource Include="Images\More Cosmon.png" />
    <Resource Include="Images\Natural satellite.png" />
    <Resource Include="Images\Nebula+.png" />
    <Resource Include="Images\Nebula.png" />
    <Resource Include="Images\Neutron star.png" />
    <Resource Include="Images\Neutronium.png" />
    <Resource Include="Images\Nucleation toggle.png" />
    <Resource Include="Images\Ocean world.png" />
    <Resource Include="Images\Ocean.png" />
    <Resource Include="Images\Offline.png" />
    <Resource Include="Images\Orange dwarf.png" />
    <Resource Include="Images\Particle+.png" />
    <Resource Include="Images\Particle.png" />
    <Resource Include="Images\Planet.png" />
    <Resource Include="Images\Planetesimal.png" />
    <Resource Include="Images\Pond.png" />
    <Resource Include="Images\Preon.png" />
    <Resource Include="Images\Protogalaxy.png" />
    <Resource Include="Images\Protoplanet.png" />
    <Resource Include="Images\Protostar.png" />
    <Resource Include="Images\Puddle big.png" />
    <Resource Include="Images\Puddle.png" />
    <Resource Include="Images\Quark star.png" />
    <Resource Include="Images\Quarks.png" />
    <Resource Include="Images\Quasi star.png" />
    <Resource Include="Images\Rank auto.png" />
    <Resource Include="Images\Rank improvement.png" />
    <Resource Include="Images\Rank levels.png" />
    <Resource Include="Images\Rank max.png" />
    <Resource Include="Images\Rank Researches.png" />
    <Resource Include="Images\Rank toggle.png" />
    <Resource Include="Images\Red giant+.png" />
    <Resource Include="Images\Red giant.png" />
    <Resource Include="Images\Red supergiant.png" />
    <Resource Include="Images\ResearchA1.png" />
    <Resource Include="Images\ResearchA2.png" />
    <Resource Include="Images\ResearchA3.png" />
    <Resource Include="Images\ResearchA4.png" />
    <Resource Include="Images\ResearchA5.png" />
    <Resource Include="Images\ResearchA6.png" />
    <Resource Include="Images\ResearchA7.png" />
    <Resource Include="Images\ResearchA8.png" />
    <Resource Include="Images\ResearchA9.png" />
    <Resource Include="Images\ResearchAuto1.png" />
    <Resource Include="Images\ResearchAuto2.png" />
    <Resource Include="Images\ResearchAuto3.png" />
    <Resource Include="Images\ResearchClouds1.png" />
    <Resource Include="Images\ResearchClouds2.png" />
    <Resource Include="Images\ResearchClouds3.png" />
    <Resource Include="Images\ResearchClouds4.png" />
    <Resource Include="Images\ResearchClouds5.png" />
    <Resource Include="Images\ResearchCollapse1.png" />
    <Resource Include="Images\ResearchCollapse2.png" />
    <Resource Include="Images\ResearchCollapse3.png" />
    <Resource Include="Images\ResearchCollapse4.png" />
    <Resource Include="Images\ResearchD1.png" />
    <Resource Include="Images\ResearchD1_L.png" />
    <Resource Include="Images\ResearchD2.png" />
    <Resource Include="Images\ResearchD3.png" />
    <Resource Include="Images\ResearchD3_L.png" />
    <Resource Include="Images\ResearchD4.png" />
    <Resource Include="Images\ResearchD5.png" />
    <Resource Include="Images\ResearchDark1.png" />
    <Resource Include="Images\ResearchDark1_L.png" />
    <Resource Include="Images\ResearchDark2.png" />
    <Resource Include="Images\ResearchDark3.png" />
    <Resource Include="Images\ResearchDark4.png" />
    <Resource Include="Images\ResearchDark4_L.png" />
    <Resource Include="Images\ResearchDark5.png" />
    <Resource Include="Images\ResearchEnergy1.png" />
    <Resource Include="Images\ResearchEnergy2.png" />
    <Resource Include="Images\ResearchEnergy3.png" />
    <Resource Include="Images\ResearchEnergy4.png" />
    <Resource Include="Images\ResearchEnergy5.png" />
    <Resource Include="Images\ResearchEnergy6.png" />
    <Resource Include="Images\ResearchG1.png" />
    <Resource Include="Images\ResearchG2.png" />
    <Resource Include="Images\ResearchG3.png" />
    <Resource Include="Images\ResearchG4.png" />
    <Resource Include="Images\ResearchGalaxy1.png" />
    <Resource Include="Images\ResearchGalaxy2.png" />
    <Resource Include="Images\ResearchGalaxy3.png" />
    <Resource Include="Images\ResearchGalaxy4.png" />
    <Resource Include="Images\ResearchQ1.png" />
    <Resource Include="Images\ResearchQ2.png" />
    <Resource Include="Images\ResearchQ3.png" />
    <Resource Include="Images\ResearchQ4.png" />
    <Resource Include="Images\ResearchQ5.png" />
    <Resource Include="Images\ResearchQ6.png" />
    <Resource Include="Images\ResearchRank1.png" />
    <Resource Include="Images\ResearchRank2.png" />
    <Resource Include="Images\ResearchRank3.png" />
    <Resource Include="Images\ResearchRank4.png" />
    <Resource Include="Images\ResearchRank5.png" />
    <Resource Include="Images\ResearchRank6.png" />
    <Resource Include="Images\ResearchS1.png" />
    <Resource Include="Images\ResearchS2.png" />
    <Resource Include="Images\ResearchS3.png" />
    <Resource Include="Images\ResearchS4.png" />
    <Resource Include="Images\ResearchS5.png" />
    <Resource Include="Images\ResearchS6.png" />
    <Resource Include="Images\ResearchW1.png" />
    <Resource Include="Images\ResearchW2.png" />
    <Resource Include="Images\ResearchW3.png" />
    <Resource Include="Images\ResearchW4.png" />
    <Resource Include="Images\ResearchW5.png" />
    <Resource Include="Images\ResearchW6.png" />
    <Resource Include="Images\Sea.png" />
    <Resource Include="Images\Spread 2.png" />
    <Resource Include="Images\Spread.png" />
    <Resource Include="Images\Stability.png" />
    <Resource Include="Images\Stage auto.png" />
    <Resource Include="Images\Stage toggle.png" />
    <Resource Include="Images\Stage.png" />
    <Resource Include="Images\Stage1 border.png" />
    <Resource Include="Images\Stage2 border.png" />
    <Resource Include="Images\Stage3 border.png" />
    <Resource Include="Images\Stage4 border.png" />
    <Resource Include="Images\Stage5 border.png" />
    <Resource Include="Images\Stage6 border.png" />
    <Resource Include="Images\Star cluster denser.png" />
    <Resource Include="Images\Star cluster.png" />
    <Resource Include="Images\Stars.png" />
    <Resource Include="Images\Strange growth.png" />
    <Resource Include="Images\Strange Quarks many.png" />
    <Resource Include="Images\Strange Quarks.png" />
    <Resource Include="Images\Strangelets many.png" />
    <Resource Include="Images\Strangelets.png" />
    <Resource Include="Images\Subsatellite.png" />
    <Resource Include="Images\System red.png" />
    <Resource Include="Images\Time fast.png" />
    <Resource Include="Images\Time.png" />
    <Resource Include="Images\Universe.png" />
    <Resource Include="Images\UpgradeA1.png" />
    <Resource Include="Images\UpgradeA10.png" />
    <Resource Include="Images\UpgradeA11.png" />
    <Resource Include="Images\UpgradeA12.png" />
    <Resource Include="Images\UpgradeA13.png" />
    <Resource Include="Images\UpgradeA14.png" />
    <Resource Include="Images\UpgradeA2.png" />
    <Resource Include="Images\UpgradeA3.png" />
    <Resource Include="Images\UpgradeA4.png" />
    <Resource Include="Images\UpgradeA5.png" />
    <Resource Include="Images\UpgradeA6.png" />
    <Resource Include="Images\UpgradeA7.png" />
    <Resource Include="Images\UpgradeA8.png" />
    <Resource Include="Images\UpgradeA9.png" />
    <Resource Include="Images\UpgradeD1.png" />
    <Resource Include="Images\UpgradeD1_L.png" />
    <Resource Include="Images\UpgradeG1.png" />
    <Resource Include="Images\UpgradeG2.png" />
    <Resource Include="Images\UpgradeG3.png" />
    <Resource Include="Images\UpgradeG4.png" />
    <Resource Include="Images\UpgradeG5.png" />
    <Resource Include="Images\UpgradeG6.png" />
    <Resource Include="Images\UpgradeG7.png" />
    <Resource Include="Images\UpgradeQ1.png" />
    <Resource Include="Images\UpgradeQ10.png" />
    <Resource Include="Images\UpgradeQ11.png" />
    <Resource Include="Images\UpgradeQ2.png" />
    <Resource Include="Images\UpgradeQ3.png" />
    <Resource Include="Images\UpgradeQ3_A.png" />
    <Resource Include="Images\UpgradeQ4.png" />
    <Resource Include="Images\UpgradeQ4_A.png" />
    <Resource Include="Images\UpgradeQ5.png" />
    <Resource Include="Images\UpgradeQ5_A.png" />
    <Resource Include="Images\UpgradeQ6.png" />
    <Resource Include="Images\UpgradeQ7.png" />
    <Resource Include="Images\UpgradeQ8.png" />
    <Resource Include="Images\UpgradeQ9.png" />
    <Resource Include="Images\Upgrades auto.png" />
    <Resource Include="Images\UpgradeS1.png" />
    <Resource Include="Images\UpgradeS2.png" />
    <Resource Include="Images\UpgradeS3.png" />
    <Resource Include="Images\UpgradeS4.png" />
    <Resource Include="Images\UpgradeS5.png" />
    <Resource Include="Images\UpgradeW1.png" />
    <Resource Include="Images\UpgradeW2.png" />
    <Resource Include="Images\UpgradeW3.png" />
    <Resource Include="Images\UpgradeW4.png" />
    <Resource Include="Images\UpgradeW5.png" />
    <Resource Include="Images\UpgradeW6.png" />
    <Resource Include="Images\UpgradeW7.png" />
    <Resource Include="Images\UpgradeW8.png" />
    <Resource Include="Images\UpgradeW9.png" />
    <Resource Include="Images\Vaporization auto.png" />
    <Resource Include="Images\Vaporization improvement.png" />
    <Resource Include="Images\Vaporization toggle.png" />
    <Resource Include="Images\Void.png" />
    <Resource Include="Images\Water+.png" />
    <Resource Include="Images\Water.png" />
    <Resource Include="Images\White dwarf.png" />
  </ItemGroup>

</Project>
